<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="magni_base_gazebo">
    <gazebo reference="base_link">
    <!-- <material>Gazebo/Blue</material> -->
    </gazebo>

    <gazebo reference="sign_pole_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <gazebo reference="base_footprint">
      <kp>100000000.0</kp>
      <kd>10.0</kd>
      <mu1>0.1</mu1>
      <mu2>0.1</mu2>
      <fdir1>1 0 0</fdir1>
      <maxVel>10.0</maxVel>
      <minDepth>0.0005</minDepth>
      <laserRetro>0</laserRetro>
    </gazebo>

    <xacro:unless value="$(arg use_ros_control_for_base)">
      <gazebo>
        <plugin name="diff_dirve_controller" filename="libgazebo_ros_diff_drive.so">
          <commandTopic>mobile_base_controller/cmd_vel</commandTopic>
          <odometryTopic>odom</odometryTopic>
          <odometryFrame>odom</odometryFrame>
          <robotBaseFrame>base_footprint</robotBaseFrame>
          <publishWheelTF>false</publishWheelTF>
          <publishTf>true</publishTf>
          <publishWheelJointState>true</publishWheelJointState>
          <legacyMode>false</legacyMode>
          <updateRate>30</updateRate>
          <leftJoint>wheel_left_joint</leftJoint>
          <rightJoint>wheel_right_joint</rightJoint>
          <wheelSeparation>${wheel_separation}</wheelSeparation>
          <wheelDiameter>${wheel_radius*2}</wheelDiameter>
          <wheelAcceleration>1</wheelAcceleration>
          <wheelTorque>10</wheelTorque>
          <rosDebugLevel>na</rosDebugLevel>
        </plugin>
      </gazebo>
    </xacro:unless>

  </xacro:macro>


</robot>
